# Generated by Django 6.0.4 on 2026-04-22 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bidding", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Auction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("PAUSED", "Paused"),
                            ("ENDED", "Ended"),
                        ],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
