# Generated by Django 6.0.3 on 2026-03-29 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('vehicle_type', models.CharField(choices=[('Car', 'Car'), ('Van', 'Van'), ('Motorcycle/Scooter', 'Motorcycle/Scooter'), ('Three Wheeler', 'Three Wheeler'), ('Lorry', 'Lorry')], max_length=50)),
                ('condition', models.CharField(choices=[('Brand New', 'Brand New'), ('Registered', 'Registered'), ('Unregistered', 'Unregistered')], max_length=50)),
                ('fuel_type', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid'), ('Other', 'Other')], max_length=50)),
                ('mileage', models.IntegerField(help_text='Mileage in km')),
                ('starting_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='car_images/')),
                ('seller_contact', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_sold', models.BooleanField(default=False)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
