# Generated by Django 5.2.12 on 2026-04-24 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_carimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
